name: CI

on:
    push:
        branches:
            - main
    pull_request:
        types: [opened, synchronize, reopened, closed]
        branches:
            - main

permissions:
    contents: write # to be able to publish a GitHub release
    issues: write # to be able to comment on released issues
    pull-requests: write # to be able to comment on released pull requests

jobs:
    build:
        name: Build
        if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                  submodules: true
                  fetch-depth: 0
                  persist-credentials: false

            - uses: nrwl/nx-set-shas@v4

            - uses: actions/setup-node@v3
              with:
                  node-version: 20
                  cache: "npm"

            - run: npm ci

            - run: npx nx format:check --verbose

            - run: npx nx affected -t lint test

            - run: npx nx affected -t e2e

            - run: npx nx run-many -t build --configuration=production --parallel=3

            - name: Semantic Release
              uses: cycjimmy/semantic-release-action@v4
              env:
                  GH_TOKEN: ${{ secrets.GH_PAT_TOKEN }}
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            - name: Do something when a new release published
              if: steps.semantic.outputs.new_release_published == 'true'
              run: |
                  echo ${{ steps.semantic.outputs.new_release_version }}
                  echo ${{ steps.semantic.outputs.new_release_major_version }}
                  echo ${{ steps.semantic.outputs.new_release_minor_version }}
                  echo ${{ steps.semantic.outputs.new_release_patch_version }}
